### ISSUE TITLE
remark-gemoji or remark-emoji: which is it?

### ISSUE THREAD

**Issue by wooorm** [jackycute/remark-gemoji#1]
Both are used throughout this project, pick one :wink: (I prefer `-gemoji`)

**Comment by jackycute** [comment]
I thought I have changed all words to `-gemoji` already.

I also prefer `-gemoji` because the emoji have lots of branches.
And this project now use gemoji which is a github version.

**Comment by wooorm** [comment]
Ah okay, though, the readme still mentioned `-emoji` :)

**Comment by jackycute** [comment]
Oh, it's my mistake.
You're awesome.
Closed by cb1f6a49e92acba5d4ea2e938a93b21728b04088
