### ISSUE TITLE
Publish!

### ISSUE THREAD

**Issue by wooorm** [jackycute/remark-gemoji#3]
Hey Cheng-Han,

How’s life? How’s hackmd?

I’d love to get this remark plug-in ready for use by others. Are you still interested in getting this off the ground? If so, I’d suggest updating the Readme with some useful information, and publishing to npm :)

If you don‘t have the time at the moment, I may be able to help, if you give me GH / npm access I can do this for you.

(P.S. in a sec, I’m posting another issue, so wait ’till then :wink:)

**Comment by jackycute** [comment]
Hi, I'm good, just get slow down a bit and be able to work on these projects again!
Thanks for asking, hope you doing good too.

I would like to help to publish this plugin, but I have no experience how to do that.
Could you please provide some information how to do that?

I get you in the repo now.

**Comment by wooorm** [comment]
Thanks! Let me know when you’re online, then we can chat and I can help you through publishing to npm!

**Comment by jackycute** [comment]
I am here!

**Comment by wooorm** [comment]
OK, we can chat about it on Gitter or Hangouts, but could you first read my comment: https://github.com/jackycute/remark-gemoji/issues/4#issuecomment-183923918?

**Comment by jackycute** [comment]
https://gitter.im/jackycute/remark-gemoji

**Comment by jackycute** [comment]
https://www.npmjs.com/package/remark-gemoji-to-emoji
