### ISSUE TITLE
Change unicode emoji to gemoji shortcodes

### ISSUE THREAD

**Issue by wooorm** [jackycute/remark-gemoji#4]
Some users want to keep their emoji as gemoji shortcodes: `👍` >  `:+1:`.

I suggest splitting this plug-in in two (well, as it stands this project covers one part). Namely, a tool which transforms shortcodes into unicode (this project, `:+1:` > `👍`), and another which transforms unicode into shortcodes (another project, `👍` >  `:+1:`).

Having two projects means people can transform gemoji into emoji, let it process normally by other plug-ins, and then transform back into gemoji later.

Now, just for naming, I’m not sure how to name these, maybe `remark-gemoji-to-emoji` and `remark-emoji-to-gemoji`, but then I’m unsure what a project named `remark-gemoji` should do. :anguished:

Any thoughts? Were you able to work on emoji to HTML images?

**Comment by jackycute** [comment]
Yes, I will soon be able to work on this again :smile: 
I would like to make any of above projects.

Maybe rename this repo to `remark-emoji-gemoji`?
`remark-gemoji-emoji` for transform gemoji shortcodes to emoji unicodes.
And another repo named `remark-emoji-image` for transform emoji unicodes to HTML images.

Though that mean we need to use more plugins for all emoji transforms but will gain better flexibility.

BTW, I figure out how to do emoji to HTML images few days ago.

**Comment by wooorm** [comment]
Okay, I’ve done some thinking and I’d say we need three projects:
- `remark-gemoji`, which hooks into the remark parser and ensures gemoji shortcuts are read properly;
- `remark-gemoji-to-emoji`, which is this project, transforming `:+1:` > `👍`;
- `remark-emoji-to-gemoji`, which does the inverse, transforming `👍` > `:+1:`.

...and in the future, `remark-html-emoji-image`, which renders emoji as an image in HTML.

(the names are up for debate).

**Comment by jackycute** [comment]
OK, got it, agreed with all the namings :smile: 

I haven't know how to do `remark-gemoji`.
But others are in the range.

**Comment by wooorm** [comment]
I can de remark-gemoji! It’s probably pretty hard and it definitely is undocumented!

**Comment by jackycute** [comment]
Haha, then I will do `remark-gemoji-to-emoji` `remark-emoji-to-gemoji` and `remark-html-emoji-image`.
:100: 

Then might need start from renaming?

**Comment by jackycute** [comment]
`remark-gemoji-to-emoji` https://github.com/jackycute/remark-gemoji-to-emoji
`remark-emoji-to-gemoji` https://github.com/jackycute/remark-emoji-to-gemoji

**Comment by wooorm** [comment]
Coool! :+1: Then I’m guessing this can be closed? Awesome work, only the `remark-html-emoji-image` left?

**Comment by jackycute** [comment]
Totally! :100: 
Only `remark-html-emoji-image` need to be done.
